apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-tomaszorlo-pl-tls
spec:
  secretName: k8s-tomaszorlo-pl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
commonName: k8s.tomaszorlo.pl
dnsNames:
  - k8s.tomaszorlo.pl
acme:
  config:
    - http01:
        ingressClass: nginx
      domains:
        - k8s.tomaszorlo.pl
